---
abstract: "It's new $module"
author:
  - 'Patrick Kilter <pas.freelance@googlemail.com>'
build_requires:
  Test::More: '0.98'
configure_requires:
  Module::Build::Tiny: '0.035'
dynamic_config: 0
generated_by: 'Minilla/v2.4.1, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: DBIx-Class-Elasticsearch
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  DBIx::Class::Elasticsearch:
    file: lib/DBIx/Class/Elasticsearch.pm
    version: '0.01'
requires:
  DBIx::Class: '0'
  Moose::Role: '0'
  Search::Elasticsearch: '0'
  perl: '5.008001'
version: '0.01'
x_contributors:
  - 'Sales User <sales@nydsosweb6.(none)>'
  - 'Chris Shepherd <cshepherd@about.com>'
  - 'Jens Gassmann <jens.gassmann@atomix.de>'
